Finding age 
select round(((sysdate-DOB)/365)) as age from F21_S001_8_PERSON;


-------------having, group by --------------------------------
-------1)--how many hours does a member play for sports.-----------------

Select p.fname, p.lname,p.email_id, m.member_id,sf.sport_name,(ma.EQUIPMENT_CHECKOUT-ma.EQUIPMENT_CHECKIN) as hours
 from F21_S001_8_PERSON p,F21_S001_8_MEMBER m,F21_S001_8_SPORTS_FACILITY sf, F21_S001_8_MEMBER_ACTIVITY ma where sf.sport_id=ma.sport_id and m.email_id=p.email_id and m.member_id=ma.member_id;

---------------------rollup-----------------------
----1)----------------------
Select TS.EVENT_ID, (ts.sales*ts.price)as revenue,ts.sales,ts.price as sells from F21_S001_8_SPORTS_SCHEDULE ss join F21_S001_8_EVENT_TICKET_SALES ts on ss.event_id=ts.event_id  group by rollup(ts.SALES ,ts.PRICE);
----2)----------------------



-----------over--------------------
------1)--------------------------
--mean:-gives us the total amount of revenue generated by each sport from the ticket sells of those events.
--query:
Select sd.sport_id,sum(ts.sales)  over (order by sd.event_id) as sells from F21_S001_8_SPORTS_SCHEDULE sd join F21_S001_8_EVENT_TICKET_SALES ts on sd.event_id=ts.event_id;
-----2)-------
--mean: statistics of popular membership plan
--query:
Select DESCRIPTION,count(mp.plan_id) as TOTAL_MEMBERS  from F21_S001_8_MEMBER m join F21_S001_8_MEMBERSHIP_PLAN mp  On m.plan_id=mp.plan_id group by m.plan_id,DESCRIPTION  ORDER BY TOTAL_MEMBERS DESC;

---------

SELECT FNAME, LNAME, SALARY 
FROM F21_S001_8_EMPLOYEE E, F21_S001_8_PERSON P
WHERE SEX='F' AND P.EMAIL_ID=E.EMAIL_ID AND E.EMAIL_ID IN 
(SELECT EMAIL_ID FROM F21_S001_8_EMPLOYEE WHERE SALARY>20) GROUP BY FNAME,LNAME,SALARY;



SELECT FNAME, LNAME, SALARY ,(
		select round(((sysdate-DOB)/365))  from  F21_S001_8_PERSON  where email_id=e.email_id
	) as Age 
FROM F21_S001_8_EMPLOYEE E, F21_S001_8_PERSON P
WHERE SEX='F' AND P.EMAIL_ID=E.EMAIL_ID AND E.EMAIL_ID IN 
(SELECT EMAIL_ID FROM F21_S001_8_EMPLOYEE WHERE SALARY>20) ;
------------



select sex, m.plan_id,cost
from F21_S001_8_PERSON p, F21_S001_8_MEMBER m ,F21_S001_8_MEMBERSHIP_PLAN mp
where p.email_id=m.email_id AND m.plan_id=mp.plan_id
GROUP by cube(sex,m.plan_id,cost);





select I.ID, I.NAME, I.DEPARTMENT, I.SALARY from
(select avg(BUDGET) as averageBudget from DEPARTMENT) as BUDGET, Instructor as I
where I.SALARY > BUDGET.averageBudget;

SELECT distinct e.employee_id,p.fname,p.lname,p.apartment_number,p.street,p.city,p.state,p.zip,p.dob,p.sex, round(((sysdate-p.DOB)/365)) as age, SALARY from 
(	select event_manager_id as emi from F21_S001_8_SPORTS_SCHEDULE)  , F21_S001_8_EMPLOYEE e, F21_S001_8_PERSON p
WHERE e.employee_id=emi and p.email_id=e.email_id;