-- Team 8 
-- uta ids:1001933530, 1001945949
-- name:adit shah, jaykumar patel
-----------------1
CREATE TABLE F21_S001_8_PERSON(
	EMAIL_ID 	varchar(25) 	not null,
	FNAME	 	varchar(10) 	not null,
	LNAME	 	varchar(10) 	not null,
	DOB	 	date ,
	SEX 		char(1),
	STREET  	varchar(30) 	not null,
	APARTMENT_NUMBER varchar(5),
	CITY 		varchar(15)	not null,
	STATE 		varchar(10) 	not null,
	ZIP 		varchar(5)	not null,
	primary key(EMAIL_ID),
	check( SEX='F' OR SEX='M')
);
-------------2
CREATE TABLE F21_S001_8_PERSON_CONTACT(
	EMAIL_ID 	varchar(25) 	not null,
	PHONE_NUMBER 	varchar(10)		not null unique,
	primary key(EMAIL_ID,PHONE_NUMBER),
	foreign key(EMAIL_ID) references F21_S001_8_PERSON(EMAIL_ID) on delete cascade
);
--------------3 
CREATE TABLE F21_S001_8_MEMBERSHIP_PLAN(
	PLAN_ID 	INT 		NOT NULL,
	DESCRIPTION	VARCHAR(25)	NOT NULL,
	COST		VARCHAR(5)		NOT NULL,
	AMMUNITIES	VARCHAR(75),
	PRIMARY KEY(PLAN_ID)
);
----------------4
CREATE TABLE F21_S001_8_MEMBER(
	MEMBER_ID	INT	NOT NULL,
	-- EQUIPMENT_ID	VARCHAR(7)		NOT NULL,
	EMAIL_ID	varchar(25) 	not null,
	PLAN_ID		INT		NOT NULL,
	PRIMARY KEY(MEMBER_ID),
	FOREIGN KEY(EMAIL_ID) 		references F21_S001_8_PERSON(EMAIL_ID)
		on delete cascade,
	FOREIGN KEY(PLAN_ID)		references F21_S001_8_MEMBERSHIP_PLAN(PLAN_ID)
		on delete cascade
);
-----------------5
CREATE TABLE F21_S001_8_SPORTS_FACILITY(
	SPORT_ID	INT NOT NULL,
	SPORT_NAME	VARCHAR(10)	NOT NULL,
	INSPECTED_DATE	DATE	NOT NULL,
	-- EMIAL_ID	VARCHAR(25) DEFAULT  NULL,
	-- MEMBER_ID	varchar(7)	DEFAULT  NULL,
	-- CURRENT_OCCUPANT VARCHAR(10)	DEFAULT  NULL,
	PRIMARY KEY(SPORT_ID)
	-- FOREIGN KEY(MEMBER_ID)	REFERENCES F21_S001_8_MEMBER(MEMBER_ID)
	-- 	on delete cascade
);
-------------6 
CREATE TABLE F21_S001_8_SPORTS_LOCATION_ID(
	SPORT_ID	INT		NOT NULL ,
	LOCATION_ID	VARCHAR(50)	NOT NULL,
	PRIMARY KEY(LOCATION_ID),
	FOREIGN KEY(SPORT_ID) REFERENCES F21_S001_8_SPORTS_FACILITY(SPORT_ID)
		on delete cascade
);
-------------7
	CREATE TABLE F21_S001_8_EQUIPMENT_MAINTANENCE(
		EQUIPMENT_ID	INT		NOT NULL,
		SPORT_ID	INT		NOT NULL,
		EQUIPMENT_NAME	VARCHAR(15)	NOT NULL,
		CONDITION	VARCHAR(5),
		AVAILABILITY	VARCHAR(5),
		PRIMARY KEY(EQUIPMENT_ID),
		FOREIGN KEY(SPORT_ID) REFERENCES F21_S001_8_SPORTS_FACILITY(SPORT_ID) on delete cascade	,
			check( CONDITION='G' OR CONDITION='B' OR CONDITION='M'),
			CHECK (AVAILABILITY='Y' OR AVAILABILITY='N')
	);
----------------------------8
CREATE TABLE F21_S001_8_EMPLOYEE(
	EMPLOYEE_ID 	INT	not null,
	SALARY 		varchar(5) 		not null,
	EMAIL_ID	varchar(25) 	not null,
	primary key(EMPLOYEE_ID),
	FOREIGN KEY(EMAIL_ID)	references F21_S001_8_PERSON(EMAIL_ID) on delete cascade
);
------------------------9
CREATE TABLE F21_S001_8_SPORTS_SCHEDULE(
	EVENT_ID	INT	NOT NULL,
	EVENT_NAME	VARCHAR(30)	NOT NULL,
	SPORT_ID	INT		NOT NULL,
	LOCATION_ID	VARCHAR(5)	NOT NULL,
	START_TIME	TIMESTAMP NOT NULL,	
	EVENT_MANAGER_ID	INT	NOT NULL,
	PRIMARY KEY(EVENT_ID),
	FOREIGN KEY(SPORT_ID)	REFERENCES F21_S001_8_SPORTS_FACILITY(SPORT_ID) on delete cascade	,
	FOREIGN KEY (EVENT_MANAGER_ID) REFERENCES f21_s001_8_employee (EMPLOYEE_ID) on delete cascade
);
-----------------10
CREATE TABLE F21_S001_8_EVENT_TICKET_SALES(
	EVENT_ID	INT		NOT NULL,
	PRICE		VARCHAR(10),
	TOTAL		INT,
	SALES		INT,
	PRIMARY KEY(EVENT_ID)
);
---------------11
CREATE TABLE 	F21_S001_8_MEMBER_ACTIVITY 
(	MEMBER_ID INT , 
	EQUIPMENT_ID INT, 
	SPORT_ID INT,
	EQUIPMENT_CHECKIN TIMESTAMP NOT NULL, 
	EQUIPMENT_CHECKOUT TIME NOT NULL, 
	PRIMARY KEY(MEMBER_ID), 
	FOREIGN KEY(EQUIPMENT_ID) REFERENCES F21_S001_8_EQUIPMENT_MAINTANENCE(EQUIPMENT_ID) ON DELETE CASCADE
);
